wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1679481716.136688
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.7.15
      5: 0.13.6
      8:
      - 1
      - 5
