wandb_version: 1

CastToTensor:
  desc: null
  value: true
Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x7f8b68f42e50>
    arch: torchvision.models.resnet.resnet18
    default_cbs: true
    loss_func:
      _name: FlattenedLoss of CrossEntropyLoss()
      axis: 1
      flatten: true
      floatify: false
      is_2d: true
    lr: 0.001
    metrics:
    - <utils.MIOU object at 0x7f8b285e4350>
    - <utils.BackgroundIOU object at 0x7f8b285e4390>
    - <utils.RoadIOU object at 0x7f8b285e43d0>
    - <utils.TrafficLightIOU object at 0x7f8b285e4410>
    - <utils.TrafficSignIOU object at 0x7f8b285e4450>
    - <utils.PersonIOU object at 0x7f8b285e4490>
    - <utils.VehicleIOU object at 0x7f8b285e44d0>
    - <utils.BicycleIOU object at 0x7f8b285e4510>
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    n_out: 7
    normalize: true
    opt_func: fastai.optimizer.Adam
    path: .
    pretrained: true
    splitter: fastai.vision.learner._resnet_split
    train_bn: true
    wd: null
    wd_bn_bias: false
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
SaveModelCallback:
  desc: null
  value:
    at_end: false
    every_epoch: false
    fname: model
    with_opt: false
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: null
    log_dataset: false
    log_model: true
    log_preds: false
    log_preds_every_epoch: false
    model_name: null
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1673269335.087735
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.15
      5: 0.13.6
      8:
      - 1
      - 5
augment:
  desc: null
  value: true
batch per epoch:
  desc: null
  value: 100
batch size:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 8
dataset.tfms:
  desc: null
  value: '[Pipeline: ColReader -- {''cols'': ''image_fname'', ''pref'': '''', ''suff'':
    '''', ''label_delim'': None} -> PILBase.create, Pipeline: ColReader -- {''cols'':
    ''label_fname'', ''pref'': '''', ''suff'': '''', ''label_delim'': None} -> PILBase.create]'
device:
  desc: null
  value: cpu
dls.after_batch:
  desc: null
  value: "Pipeline: IntToFloatTensor -- {'div': 255.0, 'div_mask': 1} -> Flip -- {'size':\
    \ None, 'mode': 'bilinear', 'pad_mode': 'reflection', 'mode_mask': 'nearest',\
    \ 'align_corners': True, 'p': 0.5} -> Brightness -- {'max_lighting': 0.2, 'p':\
    \ 1.0, 'draw': None, 'batch': False} -> Normalize -- {'mean': tensor([[[[0.4850]],\n\
    \n         [[0.4560]],\n\n         [[0.4060]]]]), 'std': tensor([[[[0.2290]],\n\
    \n         [[0.2240]],\n\n         [[0.2250]]]]), 'axes': (0, 2, 3)}"
dls.after_item:
  desc: null
  value: 'Pipeline: AddMaskCodes -> Resize -- {''size'': (320, 180), ''method'': ''crop'',
    ''pad_mode'': ''reflection'', ''resamples'': (<Resampling.BILINEAR: 2>, <Resampling.NEAREST:
    0>), ''p'': 1.0} -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
epochs:
  desc: null
  value: 10
framework:
  desc: null
  value: fastai
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 2
img_size:
  desc: null
  value:
  - 180
  - 320
input 1 dim 1:
  desc: null
  value: 8
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 180
input 1 dim 4:
  desc: null
  value: 320
lr:
  desc: null
  value: 0.002
model parameters:
  desc: null
  value: 31113508
n_inp:
  desc: null
  value: 1
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
